export const ADD_REMINDER = 'ADD_REMINDER'
export const REMOVE_REMINDER = 'REMOVE_REMINDER'

export const SET_FILTER = 'SET_FILTER'
export const FILTER_ALL = 'FILTER_ALL'
export const FILTER_UPCOMING = 'FILTER_UPCOMING'
export const FILTER_NEXT_WEEK = 'FILTER_NEXT_WEEK'
