export const CREATE_REMINDER = 'CREATE_REMINDER'
export const DELETE_REMINDER = 'DELETE_REMINDER'
export const UPDATE_REMINDER = 'UPDATE_REMINDER'

export const CREATE_LABEL = 'CREATE_LABEL'
export const DELETE_LABEL = 'DELETE_LABEL'
export const UPDATE_LABEL = 'UPDATE_LABEL'
export const ASSIGN_LABEL = 'ASSIGN_LABEL'
export const UNASSIGN_LABEL = 'UNASSIGN_LABEL'

export const SET_FILTER = 'SET_FILTER'
export const CLEAR_FILTER = 'CLEAR_FILTER'

export const SET_SELECTION = 'SET_SELECTION'
export const CLEAR_SELECTION = 'CLEAR_SELECTION'
